### ISSUE TITLE
Problem with :cocomake

### ISSUE THREAD

**Issue by vendethiel** [satyr/vim-coco#1]
Hi,

It looks like the :CocoMake command is not working, because `coco` (in the CLI) already appends .co, which breaks since the file name already contains it.

**Comment by satyr** [comment]
It seems working for me. What errors are you seeing?

**Comment by vendethiel** [comment]
Ok, figured out. It happens when the file is not save yet.

**Comment by satyr** [comment]
Looks like an inherited behavior from _vim-coffee-script_. Should it auto-save?

**Comment by vendethiel** [comment]
1) auto-save
2) notice and stop
3) give the possibility to save and process, or stop
4) autosave and process

**Comment by satyr** [comment]
#### before

```
$ coco nonexistent.co
Error: ENOENT, stat 'nonexistent.co.co'
```

#### after

```
$ coco nonexistent.co
Can't find: nonexistent.co
```

**Comment by satyr** [comment]
As for auto-saving, this should help: http://stackoverflow.com/questions/8576374/how-to-make-vim-print-hint-about-save-the-unsaved-file-before-compiling
